Add chain label to Nitro metrics
OffchainLabs/community-helm-charts pull request #20
Opened 2024-02-07 13:34 UTC by lambchr

[ticket](https://www.notion.so/arbitrum/Loki-and-mimir-alerts-and-dashboards-57b0b72827c14592984b307169b6ca11?pvs=4)

Adding a chain label to the Nitro, Relay and LB service monitors. This will enable us to compare metrics within a chain against each other.

2024-02-07 17:18 UTC, a-thomas-22 requested changes
The changes center around making it clear what the value does. Since it is specifically related to the servicemonitor, I think it makes more sense to nest it there. And to take advantage of the nitro chain name if set already(but allow it to be overriden).

2024-02-07 17:18 UTC, a-thomas-22 commented on charts/nitro/templates/servicemonitor.yaml
> +          replacement: {{ .Values.chain.name }}
Nitro can have the chain name set with `configmap.data.chain.name` Lets default to that if its set and allow it to be overridden.

2024-02-07 17:18 UTC, a-thomas-22 commented on charts/das/values.yaml
> +chain:
lets nest this value under the servicemonitor top level key. Have the relabeling be conditional only if the chain name is set or have a some kind of `enabled` key for this feature. If the relabeling is conditional if the chain name is set, have the default be an empty string.

2024-02-07 17:18 UTC, a-thomas-22 commented on charts/nitro/values.yaml
> +chain:
lets nest this value under the servicemonitor top level key. Have the relabeling be conditional only if the chain name is set here or with the `configmap.data.chain.name` or have a some kind of enabled key for this feature. If the relabeling is conditional if the chain name is set, have the default be an empty string.

2024-02-07 17:18 UTC, a-thomas-22 commented on charts/relay/values.yaml
> +chain:
lets nest this value under the servicemonitor top level key. Have the relabeling be conditional only if the chain name is set or have a some kind of enabled key for this feature. If the relabeling is conditional if the chain name is set, have the default be an empty string.

2024-02-07 18:07 UTC, bhuddlestonocl reviewed
Should these changes additionally be added to `charts-publish/nitro`?

2024-02-08 16:16 UTC, a-thomas-22 commented
@bhuddlestonocl 
> Should these changes additionally be added to `charts-publish/nitro`?

`charts-publish/nitro` should be deprecated in favor of `charts-publish/offchain-nitro` except for stylus testnet(which is on its own branch). This was done in https://github.com/OffchainLabs/sre-helm-charts/pull/1286

That new offchain-nitro uses this as a dependency so we should only need to update it here and then add whatever global overrides we want in `offchain-nitro`

2024-02-08 16:43 UTC, merged